
[functions.assistant-router]
enabled = true
verify_jwt = false
import_map = "./functions/assistant-router/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/assistant-router/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/assistant-router/*.html" ]

[functions.finance-advisor]
enabled = true
verify_jwt = true
import_map = "./functions/finance-advisor/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/finance-advisor/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/finance-advisor/*.html" ]
