-- ==============================================================================
-- SCHEMA SUPABASE: ECOSSISTEMA ARNALDO TRENTIN
-- Execute este script no "SQL Editor" do seu Supabase (https://tmpwmtpdxcvulglkahcg.supabase.co)
-- ==============================================================================

-- 1. Criação da Tabela de Clientes [01_Clientes]
CREATE TABLE IF NOT EXISTS clientes (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    nome_cliente VARCHAR(255) NOT NULL,
    whatsapp VARCHAR(20),
    endereco_completo TEXT,
    documento_cpf_cnpj VARCHAR(20),
    relato_necessidade TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Criação do Tipo ENUM para os Status da IA
-- DROPa antes para evitar erro de Type Already Exists (opcional se for criação do zero)
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'status_ia') THEN
        CREATE TYPE status_ia AS ENUM ('Aberto', 'Em Campo', 'Validado', 'Finalizado');
    END IF;
END $$;

-- 3. Criação da Tabela de Ordens de Serviço [02_Ordem_Servico]
CREATE TABLE IF NOT EXISTS ordens_servico (
    id_os BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Auto-incremento
    cliente_id UUID REFERENCES clientes(id) ON DELETE CASCADE, -- Vinculo Relacional
    vendedor VARCHAR(100), -- Dropdown Alfabética
    servico_tipo VARCHAR(150),
    materiais_lista TEXT, -- Texto ou JSONB
    colaborador VARCHAR(100), -- Dropdown: Arnaldo, Ajudante 1, Ajudante 2, etc
    data_hora TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    status_ia status_ia DEFAULT 'Aberto', -- Enum que nós criamos
    pasta_midia_instagram TEXT[], -- Array de URLs das mídias
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==============================================================================
-- 4. POLÍTICAS DE SEGURANÇA (Row Level Security)
-- ==============================================================================
-- O Supabase usa RLS bloqueado por padrão nas APIs (quando configurado no painel).
-- Para integrações com IA via API Key, muitas vezes é necessário liberar o insert/update anônimo:

ALTER TABLE clientes ENABLE ROW LEVEL SECURITY;
ALTER TABLE ordens_servico ENABLE ROW LEVEL SECURITY;

-- IMPORTANTE: Políticas abertas para fins de integração via código neste início.
-- Assim que validar os agentes, mude as políticas para usuários autenticados (JWT).
CREATE POLICY "Permitir acesso anônimo total a clientes" 
ON clientes FOR ALL USING (true);

CREATE POLICY "Permitir acesso anônimo total as OS" 
ON ordens_servico FOR ALL USING (true);
